name: tabmind
description: tabmind app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.0
  freezed_annotation: ^2.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_serializable: ^6.2.0
  dio: ^4.0.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.2
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
