name: tabmind
description: tabmind app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.0
  freezed_annotation: ^2.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_serializable: ^6.2.0
  dio: ^4.0.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.6
  flutter_local_notifications: ^9.5.3+1
  rxdart: ^0.27.5
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.2
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tabmind-logos/Logo-Black-removedbg.png
    - assets/tabmind-logos/Logo-Red-removedbg.png
    - assets/tabmind-logos/Logo-Pill-Black-removedbg.png
    - assets/tabmind-logos/Logo-Pill-Red-removedbg.png
    - assets/images/bell.PNG
    - assets/images/background.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
