// This file is "main.dart"
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'creationPage_model.freezed.dart';

@freezed
class CreationPageModel with _$CreationPageModel {
  const factory CreationPageModel({
    required String name,
    required String dosis,
    required String frequency,
    required String importance,
    required String details,
    required TimeOfDay timeOfDay,
    required bool status,
  }) = _CreationPageModel;
}