// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'creationPage_model.freezed.dart';

@freezed
class CreationPageModel with _$CreationPageModel {
  const factory CreationPageModel() = _CreationPageModel;
}