// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';
import 'package:tabmind/pages/reminderPage/reminderPage_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profiles_model.freezed.dart';

part 'profiles_model.g.dart';

@freezed
class ProfilesModel with _$ProfilesModel {
  @HiveType(typeId: 0, adapterName: 'ProfileModelAdapter')
  const factory ProfilesModel({
    @HiveField(0) required String profileName,
    @HiveField(1) required bool active,
    @HiveField(2) required List<ReminderPageModel> reminders,
  }) = _ProfilesModel;
}