// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profiles_model.freezed.dart';

@freezed
class ProfilesModel with _$ProfilesModel {
  const factory ProfilesModel() = _ProfilesModel;
}