// This file is "main.dart"
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'reminderPage_model.freezed.dart';

@freezed
class ReminderPageModel with _$ReminderPageModel {
  const factory ReminderPageModel({
    required String name,
    required String dosis,
    required String frequency,
    required String importance,
    required String details,
    required TimeOfDay timeOfDay,
  }) = _ReminderPageModel;
}