// This file is "main.dart"
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'reminderPage_model.freezed.dart';

part 'reminderPage_model.g.dart';

@freezed
class ReminderPageModel with _$ReminderPageModel {
  @HiveType(typeId: 1, adapterName: 'ReminderPageModelAdapter')
  const factory ReminderPageModel({
    @HiveField(0) required String name,
    @HiveField(1) required String dosis,
    @HiveField(2) required String frequency,
    @HiveField(3) required String importance,
    @HiveField(4) required String details,
    @HiveField(5) required TimeOfDay timeOfDay,
    @HiveField(6) required bool status,
  }) = _ReminderPageModel;
}